#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
virtual_environment="${STERILE_VENV:-$HOME/data/venvs/sterile-py311}"
output_root="${STERILE_SERVER_OUTPUT_ROOT:-$HOME/data/outputs/miniboone_reprofile_toy}"
total_grid_points=36100

usage() {
    echo "Usage: $0 start BATCH [WORKERS=56] [TOYS=10000]"
    echo "       $0 status BATCH"
    echo "       $0 watch BATCH [SECONDS=10]"
    echo "       $0 stop BATCH"
}

format_seconds() {
    local seconds=${1%.*}
    if (( seconds < 0 )); then seconds=0; fi
    printf '%02dd %02dh %02dm %02ds' \
        $((seconds / 86400)) $(((seconds % 86400) / 3600)) \
        $(((seconds % 3600) / 60)) $((seconds % 60))
}

batch_status() {
    local batch=$1
    local batch_directory="$output_root/$batch"
    local manifest="$batch_directory/manifest.env"
    if [[ ! -f "$manifest" ]]; then
        echo "Batch not found: $batch_directory" >&2
        return 2
    fi
    # The manifest is generated by this script and contains numeric values only.
    source "$manifest"
    local completed=0
    local file lines
    while IFS= read -r -d '' file; do
        lines=$(wc -l < "$file")
        if (( lines > 0 )); then completed=$((completed + lines - 1)); fi
    done < <(find "$batch_directory/shards" -name point_calibration.csv -print0 2>/dev/null)
    local now elapsed running finished failed percent rate eta filled empty bar
    now=$(date +%s)
    elapsed=$((now - START_EPOCH))
    running=0
    for file in "$batch_directory"/pids/*.pid; do
        [[ -e "$file" ]] || continue
        if kill -0 "$(<"$file")" 2>/dev/null; then running=$((running + 1)); fi
    done
    finished=$(find "$batch_directory/status" -name '*.done' 2>/dev/null | wc -l)
    failed=$(find "$batch_directory/status" -name '*.failed' 2>/dev/null | wc -l)
    percent=$(awk -v n="$completed" -v d="$TOTAL_POINTS" 'BEGIN{printf "%.2f",100*n/d}')
    rate=$(awk -v n="$completed" -v s="$elapsed" 'BEGIN{if(s>0) printf "%.3f",n/s; else print "0.000"}')
    if (( completed > 0 )); then
        eta=$(awk -v n="$completed" -v d="$TOTAL_POINTS" -v s="$elapsed" 'BEGIN{printf "%.0f",(d-n)*s/n}')
    else
        eta=0
    fi
    filled=$(awk -v n="$completed" -v d="$TOTAL_POINTS" 'BEGIN{printf "%d",40*n/d}')
    empty=$((40 - filled))
    bar="$(printf '%*s' "$filled" '' | tr ' ' '#')$(printf '%*s' "$empty" '' | tr ' ' '-')"
    printf '[%s] %5s%%  %d/%d points  %.3f point/s  elapsed %s  ETA %s  workers %d running, %d done, %d failed\n' \
        "$bar" "$percent" "$completed" "$TOTAL_POINTS" "$rate" \
        "$(format_seconds "$elapsed")" "$(format_seconds "$eta")" \
        "$running" "$finished" "$failed"
    if (( completed >= TOTAL_POINTS )); then return 10; fi
    if (( running == 0 && (finished + failed) >= WORKERS )); then return 11; fi
    return 0
}

action=${1:-}
case "$action" in
    start)
        batch=${2:-}
        workers=${3:-56}
        toys=${4:-10000}
        [[ "$batch" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || {
            echo "BATCH may contain only letters, digits, dot, underscore and dash" >&2
            exit 2
        }
        [[ "$workers" =~ ^[1-9][0-9]*$ ]] && (( workers <= total_grid_points )) || exit 2
        [[ "$toys" =~ ^[1-9][0-9]*$ ]] || exit 2
        [[ -x "$virtual_environment/bin/python" ]] || {
            echo "Python environment not found: $virtual_environment" >&2
            exit 2
        }
        batch_directory="$output_root/$batch"
        [[ ! -e "$batch_directory" ]] || {
            echo "Batch already exists: $batch_directory" >&2
            exit 2
        }
        mkdir -p "$batch_directory"/{logs,pids,status,shards}
        cat > "$batch_directory/manifest.env" <<EOF
BATCH=$batch
WORKERS=$workers
TOYS_PER_POINT=$toys
TOTAL_POINTS=$total_grid_points
START_EPOCH=$(date +%s)
GIT_COMMIT=$(git -C "$repository_root" rev-parse HEAD)
EOF
        for ((worker=0; worker<workers; worker++)); do
            start=$((worker * total_grid_points / workers))
            stop=$(((worker + 1) * total_grid_points / workers))
            worker_name=$(printf 'worker_%02d' "$worker")
            nohup "$0" internal-worker "$batch" "$worker_name" "$start" "$stop" "$toys" \
                > "$batch_directory/logs/$worker_name.log" 2>&1 < /dev/null &
            echo $! > "$batch_directory/pids/$worker_name.pid"
        done
        echo "Started $workers workers for $total_grid_points points x $toys Toys."
        echo "Monitor with: bash scripts/server/miniboone_reprofile_toy.sh watch $batch"
        ;;
    internal-worker)
        batch=$2; worker_name=$3; start=$4; stop=$5; toys=$6
        batch_directory="$output_root/$batch"
        export OMP_NUM_THREADS=1 OPENBLAS_NUM_THREADS=1 MKL_NUM_THREADS=1
        export NUMEXPR_NUM_THREADS=1 MPLBACKEND=Agg
        set +e
        "$virtual_environment/bin/python" -B \
            "$repository_root/studies/miniboone_coverage_pilot/run_pilot.py" \
            --toys "$toys" --start-point "$start" --stop-point "$stop" \
            --output-directory "$batch_directory/shards/$worker_name"
        exit_code=$?
        set -e
        if (( exit_code == 0 )); then
            printf '0\n' > "$batch_directory/status/$worker_name.done"
        else
            printf '%d\n' "$exit_code" > "$batch_directory/status/$worker_name.failed"
        fi
        exit "$exit_code"
        ;;
    status)
        batch_status "${2:?missing BATCH}" || code=$?
        [[ ${code:-0} == 10 ]] && exit 0
        exit "${code:-0}"
        ;;
    watch)
        batch=${2:?missing BATCH}; interval=${3:-10}
        while true; do
            set +e
            line=$(batch_status "$batch")
            code=$?
            set -e
            printf '\r\033[K%s' "$line"
            if (( code == 10 )); then printf '\nCompleted.\n'; break; fi
            if (( code == 11 )); then printf '\nStopped before completion; inspect failed workers.\n'; exit 1; fi
            sleep "$interval"
        done
        ;;
    stop)
        batch=${2:?missing BATCH}; batch_directory="$output_root/$batch"
        [[ -d "$batch_directory/pids" ]] || exit 2
        for file in "$batch_directory"/pids/*.pid; do
            [[ -e "$file" ]] || continue
            pid=$(<"$file")
            command=$(ps -p "$pid" -o args= 2>/dev/null || true)
            if [[ "$command" == *"internal-worker $batch"* ]]; then kill "$pid"; fi
        done
        echo "Stop signal sent to workers in batch $batch"
        ;;
    *) usage; exit 2;;
esac
